//"use client"
import type { Metadata } from "next";
//import { useState } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //const getCurrentTheme = () => window.matchMedia("(prefers-color-scheme: dark)").matches;
  //const [theme, setTheme] = useState(getCurrentTheme());


  return (
    <html className="theme-light" lang="en">
      <body>
        {/*theme*/}
        {children}
      </body>
    </html>
  );
}
