import type { Metadata } from "next";
import ThemeSwitch from "./_components/theme-switch";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <div className="has-text-left">
            <ThemeSwitch></ThemeSwitch>
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
